### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by natarajanrodrigues** [dadosgovbr/aplicativos-dados-brasil#11]
Prezados mantenedores, 

por gentileza, existe um 1 pull request pendente de aprovação. 

Caso haja algum problema, fico à disposição para solucionar. 

Obrigado desde já

**Comment by augusto-herrmann** [comment]
Obrigado pela sua contribuição.

Foi aceito o pull request #10 e também no [Portal Brasileiro de Dados Abertos](http://dados.gov.br/aplicativo/por-dentro-do-enem).

Abrir o pull request é suficiente. Não é necessário abrir uma issue, a não ser que haja um problema específico que precise de discussão. Às vezes pode demorar a ser analisado porque só temos uma pessoa na equipe. Assim, peço desculpas pela demora.
