### ISSUE TITLE
[removido nome produto de companhia telefonica]

### ISSUE THREAD

**Issue by armandadr** [dadosgovbr/aplicativos-dados-brasil#14]
Olá, mais alguém usou o [removido nome de produto] para a [removido nome de empresa do setor de telecomunicações]? [removido link SPAM]

**Comment by augusto-herrmann** [comment]
Olá. O objetivo deste repositório é coletar exemplos de usos de [dados abertos](http://dados.gov.br/pagina/dados-abertos) no Brasil. Não parece ser esse o caso do seu comentário e link.
