### ISSUE TITLE
Portal Dados Abertos Desatualizado

### ISSUE THREAD

**Issue by araujoetal** [dadosgovbr/aplicativos-dados-brasil#6]
Olá, 
Muito dos Apps publicados aqui não estão presentes no site: http://dados.gov.br/aplicativos
O suporte acabou?

sds,

**Comment by Chagall** [comment]
Gostaria de saber também. Fiz um pull request para adicionar um App que criei com dados abertos há 3 dias, mas ninguém falou nada ainda.

**Comment by natarajanrodrigues** [comment]
Estou com as mesmas dúvidas. Acabei de verificar que o repositório não vem aceitando os últimos pull requests.

**Comment by augusto-herrmann** [comment]
> Olá,
> Muito dos Apps publicados aqui não estão presentes no site: http://dados.gov.br/aplicativos
> O suporte acabou?

Muitos dos apps aqui não estão mais funcionando. É muito comum que eles deixem de ser suportados após meses ou anos depois de serem cadastrados. Caso tenha um questionamento sobre um exemplo em específico, por favor o indique.

> Estou com as mesmas dúvidas. Acabei de verificar que o repositório não vem aceitando os últimos pull requests.

Nossa equipe é muito pequena e o processo ainda não é automatizado. Algumas vezes o PR vem com erro e não valida o CSV. Por isso podemos demorar bastante para avaliar os pull requests.

**Comment by araujoetal** [comment]
> > Olá,
> > Muito dos Apps publicados aqui não estão presentes no site: http://dados.gov.br/aplicativos
> > O suporte acabou?
> 
> Muitos dos apps aqui não estão mais funcionando. É muito comum que eles deixem de ser suportados após meses ou anos depois de serem cadastrados. Caso tenha um questionamento sobre um exemplo em específico, por favor o indique.
> 

Opa @augusto-herrmann 
Revisei agora e realmente atualizaram.

**Comment by augusto-herrmann** [comment]
@euojeff obrigado pela revisão.

Esse estava como privado porque estava pendente de revisão. Já foi corrigido e está disponível em: http://dados.gov.br/aplicativo/bolsa-familia-info
